insert into ciudad (nombre, pais) values ('Quillo', 'Peru');
insert into ciudad (nombre, pais) values ('Palca', 'Peru');
insert into ciudad (nombre, pais) values ('Margarita', 'Colombia');
insert into ciudad (nombre, pais) values ('Embarcación', 'Argentina');
insert into ciudad (nombre, pais) values ('Santa Lucía', 'Argentina');
insert into ciudad (nombre, pais) values ('Austin', 'United States');
insert into ciudad (nombre, pais) values ('Drummondville', 'Canada');
insert into ciudad (nombre, pais) values ('El Cantón', 'Venezuela');
insert into ciudad (nombre, pais) values ('Paucarbamba', 'Peru');
insert into ciudad (nombre, pais) values ('Irricana', 'Canada');
insert into ciudad (nombre, pais) values ('Soacha', 'Colombia');
insert into ciudad (nombre, pais) values ('Jangas', 'Peru');
insert into ciudad (nombre, pais) values ('La Unión', 'Peru');
insert into ciudad (nombre, pais) values ('Guamal', 'Colombia');
insert into ciudad (nombre, pais) values ('San Felipe', 'Peru');
insert into ciudad (nombre, pais) values ('Charlottesville', 'United States');
insert into ciudad (nombre, pais) values ('Cincinnati', 'United States');
insert into ciudad (nombre, pais) values ('Chimbas', 'Argentina');
insert into ciudad (nombre, pais) values ('Tyler', 'United States');
insert into ciudad (nombre, pais) values ('Lynn', 'United States');
insert into ciudad (nombre, pais) values ('Los Andes', 'Colombia');
insert into ciudad (nombre, pais) values ('Bahía Blanca', 'Argentina');
insert into ciudad (nombre, pais) values ('Colonia Neuland', 'Paraguay');
insert into ciudad (nombre, pais) values ('North Battleford', 'Canada');
insert into ciudad (nombre, pais) values ('Pelaya', 'Colombia');
insert into ciudad (nombre, pais) values ('Atlanta', 'United States');
insert into ciudad (nombre, pais) values ('Laramate', 'Peru');
insert into ciudad (nombre, pais) values ('Penco', 'Chile');
insert into ciudad (nombre, pais) values ('Pasadena', 'United States');
insert into ciudad (nombre, pais) values ('Espinal', 'Colombia');
